/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-12-13 16:31:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cs336.pkg.*;
import java.lang.*;
import java.text.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class customerAdvancedSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("Welcome ");
      out.print(session.getAttribute("user"));
      out.write("\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<table>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<th><a href=\"customerFlights.jsp\">Flights</a></th>\n");
      out.write("\t\t<th><a href=\"customerAdvancedSearch.jsp\">Advanced Search</a></th>\n");
      out.write("\t\t<th><a href=\"customerUpcomingReservations.jsp\">Upcoming Reservations</a></th>\n");
      out.write("\t\t<th><a href=\"customerPastReservations.jsp\">Past Reservations</a></th>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h1>Flight Search</h1>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div align=\"right\"><a href='logout.jsp'>Log out</a></div>\n");
      out.write("\n");


try{
	String pmin = "";
	String pmax = "";
	String departure = "";
	String arrival = "";
	String airline = "";
	String domint = "";
	String sortby = "";
	String archive = "";
	String startdate = "";
	
	SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
	java.util.Date d = new java.util.Date();
	String today = sdf.format(d);
	
	
      out.write("\n");
      out.write("<br>\n");
      out.write("\t<form>\n");
      out.write("\tSort By:\n");
      out.write("\t\t<select name=\"sortby\" size=1>\n");
      out.write("\t\t\t<option value=\"\">(none)</option>\n");
      out.write("\t\t\t<option value=\"GROUP BY Fare, FlightNumber\">Price (low-high)</option>\n");
      out.write("\t\t\t<option value=\"GROUP BY airlineID, FlightNumber\">Airline (alphabetical)</option>\n");
      out.write("\t\t\t<option value=\"GROUP BY DepartureTime, FlightNumber\">Departure Date</option>\n");
      out.write("\t\t</select>&nbsp;<br>\n");
      out.write("\t<br>\n");
      out.write("\t<table>\n");
      out.write("\t<tr>    \n");
      out.write("\t<td>Price Min:</td><td><input type=\"number\" name=\"pmin\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td>Price Max:</td><td><input type=\"number\" name=\"pmax\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td>Origin Airport:</td><td><input type=\"text\" name=\"departure\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td>Destination Airport:</td><td><input type=\"text\" name=\"arrival\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td>Date (YYYY-MM-DD):</td><td><input type=\"text\" name=\"startdate\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td>Airline Search:</td><td><input type=\"text\" name=\"airline\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td></td><td><input type=\"radio\" name=\"domint\" value=\"\" checked=\"checked\">All | \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"domint\" value=\"dom\">Domestic | \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"domint\" value=\"int\">International</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr></tr>\n");
      out.write("\t<tr><td>Archive View:</td></tr>\n");
      out.write("\t<tr><td></td><td><input type=\"radio\" name=\"archive\" value=\"y\" checked=\"checked\">Only Future Flights | \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"archive\" value=\"\">ALL Flights</td></tr>\n");
      out.write("\t</table>\n");
      out.write("<br>\n");
      out.write("\t<input type=\"submit\" value=\"Search\">\n");
      out.write("\t</form>\n");
      out.write("\t");

		Class.forName("com.mysql.jdbc.Driver").newInstance();	
		pmin = request.getParameter("pmin");
		pmax = request.getParameter("pmax");
		if (pmax.compareTo("") == 0)
			pmax = "9999999";
		departure = request.getParameter("departure");
		arrival = request.getParameter("arrival");
		startdate = request.getParameter("startdate");
		startdate = startdate.replaceAll("-", "");
		
		airline = request.getParameter("airline");
		domint = request.getParameter("domint");
		sortby = request.getParameter("sortby");		
		archive = request.getParameter("archive");
		if (archive.compareTo("y") == 0)
			archive = "AND DepartureTime>" + today;
		
		ApplicationDB db = new ApplicationDB();
		Connection con = db.getConnection();

		Connection conn = db.getConnection();
		
		Statement statement = con.createStatement();
			String command = "SELECT FlightNumber, Fare, airlineID, departingFrom, arrivingTo, DepartureTime, ArrivalTime, dom_int FROM Flight WHERE fare<'" + pmax + "' AND fare>'" + pmin + "' AND departingFrom LIKE '%" + departure + "%' AND arrivingTo LIKE '%" + arrival + "%' AND airlineID LIKE '%" + airline + "%' AND dom_int LIKE '%" + domint + "%' AND DepartureTime>'" + startdate + "' " + archive + sortby;
		
		ResultSet result = statement.executeQuery(command);

		//Make an HTML table to show the results in:
		out.print("<table border='1'>");

		//make a row
		out.print("<tr>");
		
		//make a column
		out.print("<td>");
		out.print("Flight #");
		out.print("</td>");

		//make a column
		out.print("<td>");
		out.print("Price");
		out.print("</td>");

		//make a column
		out.print("<td>");
		out.print("Airline");
		out.print("</td>");
		
		//make a column
		out.print("<td>");
		out.print("From");
		out.print("</td>");
		
		//make a column
		out.print("<td>");
		out.print("Destination");
		out.print("</td>");

		//make a column
		out.print("<td>");
		out.print("Departure Date");
		out.print("</td>");
		
		//make a column
		out.print("<td>");
		out.print("Arrival Date");
		out.print("</td>");
		
		//make a column
		out.print("<td>");
		out.print("Domestic/International");
		out.print("</td>");
		
		out.print("</tr>");
		

		//parse out the results
		while (result.next()) {
			//userid = result.getString("userid");
			
			//make a row
			out.print("<tr>");
			
			//make a column
			out.print("<td>");
			out.print(result.getInt("FlightNumber"));
			
      out.write("\n");
      out.write("\t\t\t<form method = \"post\" action = \"customerReservation.jsp\">\t\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"FlightNum\" value = \"");
      out.print(result.getInt("FlightNumber"));
      out.write("\" />\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Details\" />\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t");

			out.print("</td>");
			
			//make a column
			out.print("<td>");
			out.print(result.getInt("Fare"));
			out.print("</td>");

			out.print("<td>");			
			out.print(result.getString("airlineID"));
			out.print("</td>");
			
			out.print("<td>");			
			out.print(result.getString("departingFrom"));
			out.print("</td>");
			
			out.print("<td>");
			out.print(result.getString("arrivingTo"));
			out.print("</td>");

			out.print("<td>");			
			out.print(result.getDate("DepartureTime"));
			out.print("</td>");
			
			out.print("<td>");			
			out.print(result.getDate("ArrivalTime"));
			out.print("</td>");
			
			out.print("<td>");			
			out.print(result.getString("dom_int"));
			out.print("</td>");
			
			out.print("</tr>");
		}
		out.print("</table>");
		
		result.close();

		statement.close();
		con.close();
} catch (Exception e){
	
}


      out.write("\n");
      out.write("<br><br>\n");
      out.write("<a href=\"success.jsp\">Home</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
