/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-12-13 17:34:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cs336.pkg.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;
import java.sql.Timestamp;

public final class repEditAirline_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("\t<form>\n");
      out.write("\tSort By:\n");
      out.write("\t<br>\n");
      out.write("\t<table>\n");
      out.write("\t<tr>\n");
      out.write("\t<td><input type=\"radio\" name=\"editType\" value=\"add\">Add | \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"editType\" value=\"delete\">Delete\n");
      out.write("\t</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>    \n");
      out.write("\t<td>Enter Airline: </td><td><input type=\"text\" name=\"airline\" value=\"\"></td>\n");
      out.write("\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t<input type=\"submit\" value=\"Edit\">\n");
      out.write("\t</form>\n");
      out.write("\t<br>\n");

	//String url = "jdbc:mysql://cs336db.cdnjviplnzua.us-east-2.rds.amazonaws.com:3306/BarBeerDrinkerSample";
	ApplicationDB db = new ApplicationDB();	
	Connection con = db.getConnection();
	//Connection conn = null;
	PreparedStatement ps = null;
	
	try {
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection conn = db.getConnection();
		String editType = request.getParameter("editType");
		String airline = request.getParameter("airline");
		
		if (editType.compareTo("add") == 0) {
		String insert = "INSERT INTO Airport '" + airline + "'";
		ps = conn.prepareStatement(insert);
		out.print(request.getParameter("user"));
		}
		else if (editType.compareTo("delete") == 0) {
		String insert = "DELETE FROM Airport '" + airline + "'";
		ps = conn.prepareStatement(insert);
		out.print(request.getParameter("user"));
		ps.setString(1, request.getParameter("airport"));
		}
		int result = 0;
        result = ps.executeUpdate();

        
      out.write("<br><a href=\"success.jsp\">Back home</a><br>\n");
      out.write("    \t<a href=\"customerFlights\">Back to FLights and Reservations page</a>\n");
      out.write("    \t");
 
	
	} catch(Exception e) {
        out.print("<p>Error connecting to MYSQL server.</p>");
        e.printStackTrace();
        out.print(e.getMessage());
    } finally {
        try { ps.close(); } catch (Exception e) {}
        try { con.close(); } catch (Exception e) {}
    }

      out.write("\n");
      out.write("<br><br><br>\n");
      out.write("<a href=\"success.jsp\">Back home</a>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
